"""
Challenge 4: Production Workflow — Claims Processing
Multi-agent orchestration workflow for ClaimSight Insurance.
"""

import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv


def _find_repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / ".env").exists():
            return parent
    return Path(__file__).resolve().parents[2]


env_path = _find_repo_root() / ".env"
load_dotenv(env_path)

PROJECT_CONNECTION_STRING = os.getenv("PROJECT_CONNECTION_STRING")
MODEL_DEPLOYMENT_NAME = os.getenv("MODEL_DEPLOYMENT_NAME", "gpt-5.4")
CLAIMS_DATA_PATH = Path(__file__).resolve().parent.parent / "challenge-1-build" / "claims_data_v3.json" #测试阶段只用1个claim

# CLAIMS = ["CLM-001", "CLM-002", "CLM-003", "CLM-004", "CLM-005"]
CLAIMS = ["VIN001",
        #    "VIN002",
        #      "VIN003",
        #        "VIN004",
        #          "VIN005"
                 ]
# TRIAGE_AGENT_NAME = "claims-triage-agent"
TRIAGE_AGENT_NAME = "churn-triage-agent"
# DECISION_AGENT_NAME = "claims-decision-agent"
DECISION_AGENT_NAME = "churn-decision-agent"

CONTENT_AGENT_NAME = "email-content-agent"
RESEND_AGENT_NAME = "auto-send-agent"

# Set WORKFLOW_AGENT_NAME in .env after creating the workflow in the Foundry portal
WORKFLOW_AGENT_NAME = os.getenv("WORKFLOW_AGENT_NAME", "")


def assess_claim(claim_id: str) -> str:
    with open(CLAIMS_DATA_PATH, "r") as f:
        data = json.load(f)
    claim = next(
        (c for c in data["claims"] if c["claim_id"] == claim_id),
        None,
    )
    if not claim:
        return json.dumps({"error": f"Claim not found: {claim_id}"})
    results = {
        "claim_id": claim["claim_id"],
        "mail_addr": claim["mail_addr"],
        # "type": claim["type"],
        # "claimant": claim["claimant"],
        "status": claim["status"],
        # "documents_submitted": claim["documents_submitted"],
        "mile": claim["vehicle_info"]["mile_today"],
        "vehicle_age_years": claim["vehicle_info"]["vehicle_age_years"],
        "warranty_expired": claim["vehicle_info"]["warrenty_expired_this_year"],
        "flags": [],
        "all_metrics": {},
    }
    for metric, reading in claim["metrics"].items():
        value = reading["value"]
        threshold = claim["thresholds"][metric]
        in_spec = threshold["min"] <= value <= threshold["max"]
        results["all_metrics"][metric] = {
            "value": value, "unit": reading["unit"],
            "min": threshold["min"], "max": threshold["max"], "in_spec": in_spec,
        }
        if not in_spec:
            if value > threshold["max"]:
                pct = ((value - threshold["max"]) / threshold["max"]) * 100
                deviation = f"{pct:.1f}% above max"
            else:
                pct = ((threshold["min"] - value) / threshold["min"]) * 100
                deviation = f"{pct:.1f}% below min"
            results["flags"].append({
                "metric": metric, "value": value,
                "unit": reading["unit"], "deviation": deviation,
            })
    return json.dumps(results, indent=2)


def send_email(
    mail_addr: str,
    subject: str,
    body: str,
) -> str:

    resend.api_key = RESEND_API_KEY

    params: resend.Emails.SendParams = {
        "from": "onboarding@resend.dev",
        "to": [mail_addr],
        "subject": subject,
        "html": body.replace("\n", "<br>"),
    }

    try:
        email = resend.Emails.send(params)

        return (
            f"Email sent successfully to {mail_addr}. "
            f"Email ID: {email.id}"
        )

    except Exception as e:
        return (
            f"Failed to send email to {mail_addr}: {str(e)}"
        )


RESEND_TOOL = FunctionTool(
    name="send_email",
    description=(
        "Send an email via Resend using the provided recipient, subject, "
        "and body. The email is sent from onboarding@resend.dev."
    ),
    parameters={
        "type": "object",
        "properties": {
            "mail_addr": {
                "type": "string",
                "description": "The recipient's email address."
            },
            "subject": {
                "type": "string",
                "description": "The email subject generated by the previous agent."
            },
            "body": {
                "type": "string",
                "description": "The email body generated by the previous agent."
            },
        },
        "required": ["mail_addr", "subject", "body"],
    },
)


def ensure_agents_deployed() -> tuple:
    """Create both agents if not already deployed; reuse existing ones."""
    print("=== Step 1: Ensure Agents Are Deployed ===")

    from azure.ai.projects import AIProjectClient
    from azure.ai.projects.models import FunctionTool, PromptAgentDefinition
    from azure.identity import DefaultAzureCredential

    assess_claim_tool = FunctionTool(
        name="assess_claim",
        description="Assess vehicle customer churn's metrics against thresholds.",
        parameters={
            "type": "object",
            "properties": {
                "claim_id": {"type": "string", "description": "Claim ID e.g. VIN001"},
            },
            "required": ["claim_id"],
        },
        strict=False,
    )

    client = AIProjectClient(
        endpoint=PROJECT_CONNECTION_STRING,
        credential=DefaultAzureCredential(),
    )
    existing_names = {a.name for a in client.agents.list()}
    if TRIAGE_AGENT_NAME not in existing_names:
        system_prompt = "You are a customer churn triage specialist for a 4S dealership under Vehicle Group. Use the assess_claim tool for each customer. Each customer has four churn metrics with acceptable ranges [min,max]. A metric is flagged if its value is outside the range; deviation is the distance outside the range. Metrics: customer_value_score (higher is better), churn_risk_score (lower is better), rfm_loyalty_score (higher is better), vehicle_usage_lifecycle_score (lower is better; higher means later lifecycle and higher churn risk). Report VIN, vehicle summary (mileage, age, warranty expired), churn risk (high/medium/low), and each flagged metric with current value, range, and deviation. Risk: high 🔴=3+ flagged, medium ⚠️=1–2, low ✅=0. Be concise and structured."
        client.agents.create_version(
            agent_name=TRIAGE_AGENT_NAME,
            definition=PromptAgentDefinition(
                model=MODEL_DEPLOYMENT_NAME,
                instructions=system_prompt,
                tools=[assess_claim_tool],
            ),
        )
        print(f"  Deployed: {TRIAGE_AGENT_NAME}")
    else:
        print(f"  Found existing: {TRIAGE_AGENT_NAME}")

    if DECISION_AGENT_NAME not in existing_names:
        system_prompt = "You are a promotion decision specialist for a 4S dealership under Vehicle Group. Input: churn triage output with VIN, churn risk (high/medium/low), flagged metrics, and vehicle info (mile_today, vehicle_age_years, warrenty_expired_this_year). Recommend exactly ONE promotion: extended_warranty_insurance if warranty expired/expiring this year and mileage <80,000 km; new_car_trade_in if mileage >=80,000 km and vehicle_age_years ==4; otherwise maintenance_package. If multiple apply, choose the promotion addressing the strongest churn signal. Explain in <=2 sentences. Format: RECOMMENDED ACTION: <action> REASONING: <1-2 sentences>"
        
        client.agents.create_version(
            agent_name=DECISION_AGENT_NAME,
            definition=PromptAgentDefinition(
                model=MODEL_DEPLOYMENT_NAME,
                instructions=system_prompt,
            ),
        )
        print(f"  Deployed: {DECISION_AGENT_NAME}")
    else:
        print(f"  Found existing: {DECISION_AGENT_NAME}")

    if CONTENT_AGENT_NAME not in existing_names:
        system_prompt = "You are a customer promotion email specialist for a 4S dealership under Vehicle Group. Input: customer VIN, churn risk, vehicle info, recommended promotion, and reasoning. Generate a concise, friendly, personalized email based strictly on the recommended promotion within 100 words. Do not change or re-evaluate the recommendation. Tailor the message to the vehicle's age, mileage, warranty status, and churn signal when relevant. Clearly explain the promotion benefit and include a natural call to action. Do not invent prices, discounts, deadlines, or other unsupported details. Format: SUBJECT: <subject> EMAIL: <email body>"
        client.agents.create_version(
            agent_name=CONTENT_AGENT_NAME,
            definition=PromptAgentDefinition(
                model=MODEL_DEPLOYMENT_NAME,
                instructions=system_prompt,
            ),
        )
        print(f"  Deployed: {CONTENT_AGENT_NAME}")
    else:
        print(f"  Found existing: {CONTENT_AGENT_NAME}")


    if RESEND_AGENT_NAME not in existing_names:
        system_prompt = (
        "You are an email sending agent. "
        "For each email provided by the previous agent, call send_email exactly once "
        "using the exact mail_addr, subject, and body values provided. "
        "Preserve all fields and content exactly; do not rewrite, summarize, regenerate, "
        "skip, or duplicate any email. "
        "The default sender is onboarding@resend.dev."
        )
                
        client.agents.create_version(
            agent_name=RESEND_AGENT_NAME,
            definition=PromptAgentDefinition(
                model=MODEL_DEPLOYMENT_NAME,
                instructions=system_prompt,
                tools=[RESEND_TOOL],
            ),
        )
        print(f"  Deployed: {RESEND_AGENT_NAME}")
    else:
        print(f"  Found Existing: {RESEND_AGENT_NAME}")


    client.close()
    return TRIAGE_AGENT_NAME, DECISION_AGENT_NAME, CONTENT_AGENT_NAME, RESEND_AGENT_NAME


def run_claims_triage(triage_agent_name: str) -> str:
    """Call the claims triage agent for all claims; handle function call loop."""
    print("\n=== Step 2a: Claims Triage ===")

    from azure.ai.projects import AIProjectClient
    from azure.identity import DefaultAzureCredential
    from openai.types.responses.response_input_param import FunctionCallOutput

    client = AIProjectClient(
        endpoint=PROJECT_CONNECTION_STRING,
        credential=DefaultAzureCredential(),
    )
    openai_client = client.get_openai_client()
    agent_ref = {"agent_reference": {"name": triage_agent_name, "type": "agent_reference"}}

    conversation = openai_client.conversations.create()
    response = openai_client.responses.create(
        input=(
            f"Assess all claims: {', '.join(CLAIMS)}. "
            "Report every metric that is outside acceptable thresholds."
        ),
        conversation=conversation.id,
        extra_body=agent_ref,
    )

    while any(item.type == "function_call" for item in response.output):
        tool_outputs = []
        for item in response.output:
            if item.type == "function_call":
                args = json.loads(item.arguments)
                result = assess_claim(args.get("claim_id", ""))
                tool_outputs.append(
                    FunctionCallOutput(
                        type="function_call_output",
                        call_id=item.call_id,
                        output=result,
                    )
                )
        response = openai_client.responses.create(
            input=tool_outputs,
            conversation=conversation.id,
            extra_body=agent_ref,
        )

    report = response.output_text
    openai_client.conversations.delete(conversation_id=conversation.id)
    client.close()
    return report


def run_claims_decision(decision_agent_name: str, claim_id: str, flags: list) -> str:
    """Call the claims decision agent for a single flagged claim."""
    from azure.ai.projects import AIProjectClient
    from azure.identity import DefaultAzureCredential

    client = AIProjectClient(
        endpoint=PROJECT_CONNECTION_STRING,
        credential=DefaultAzureCredential(),
    )
    openai_client = client.get_openai_client()
    agent_ref = {"agent_reference": {"name": decision_agent_name,
                                      "type": "agent_reference"}}

    flag_text = "\n".join(
        f"  - {f['metric']}: {f['value']} {f['unit']} ({f['deviation']})"
        for f in flags
    )
    input_text = (
        f"Claim {claim_id} has the following flags:\n"
        f"{flag_text}\n"
        "Recommend an action and give reasoning in two sentences."
    )

    conversation = openai_client.conversations.create()
    response = openai_client.responses.create(
        input=input_text,
        conversation=conversation.id,
        extra_body=agent_ref,
    )
    decision = response.output_text
    openai_client.conversations.delete(conversation_id=conversation.id)
    client.close()
    return decision


def run_mail_content(content_agent_name: str, claim_id: str, flags: list, decisions:dict) -> str:
    """Call the email content agent."""
    from azure.ai.projects import AIProjectClient
    from azure.identity import DefaultAzureCredential

    client = AIProjectClient(
        endpoint=PROJECT_CONNECTION_STRING,
        credential=DefaultAzureCredential(),
    )
    openai_client = client.get_openai_client()
    agent_ref = {"agent_reference": {"name": content_agent_name, "type": "agent_reference"}}

    flag_text = "\n".join(
        f"  - {f['metric']}: {f['value']} {f['unit']} ({f['deviation']})"
        for f in flags
    )
    decision = decisions[claim_id]
    input_text = (
        f"Claim {claim_id} has the following flags:\n"
        f"{flag_text}\n"
        f"and the recommended action is {decision}\n"
        "Generate customed promotion mail content in 150 words."
    )

    conversation = openai_client.conversations.create()
    response = openai_client.responses.create(
        input=input_text,
        conversation=conversation.id,
        extra_body=agent_ref,
    )
    content = response.output_text
    openai_client.conversations.delete(conversation_id=conversation.id)
    client.close()
    return content


def run_auto_resend(resend_agent_name: str, contents: dict) -> str:
    from azure.ai.projects import AIProjectClient
    from azure.identity import DefaultAzureCredential
    from openai.types.responses.response_input_param import FunctionCallOutput

    client = AIProjectClient(
        endpoint=PROJECT_CONNECTION_STRING,
        credential=DefaultAzureCredential(),
    )
    openai_client = client.get_openai_client()
    agent_ref = {"agent_reference": {"name": resend_agent_name, "type": "agent_reference"}}

    conversation = openai_client.conversations.create()
    response = openai_client.responses.create(
        input=(
        "For each email in EMAILS_TO_SEND, call the send_email tool exactly "
        "once using the provided mail_addr, subject, and body. "
        "Do not modify, rewrite, shorten, or regenerate the subject or body. "
        "Do not skip any email and do not send any email more than once. "
        "After processing the entire batch, summarize the number of successful "
        "and failed sends. For failures, include the claim_id and error message.\n"
        f"EMAILS_TO_SEND: {contents}"
        ),
        conversation=conversation.id,
        extra_body=agent_ref,
    )

    while any(item.type == "function_call" for item in response.output):
        tool_outputs = []
        for item in response.output:
            if item.type == "function_call":
                args = json.loads(item.arguments)
                result = send_email(mail_addr=args["mail_addr"],
                                    subject=args["subject"],
                                    body=args["body"],)
                tool_outputs.append(
                    FunctionCallOutput(
                        type="function_call_output",
                        call_id=item.call_id,
                        output=result,
                    )
                )
        response = openai_client.responses.create(
            input=tool_outputs,
            conversation=conversation.id,
            extra_body=agent_ref,
        )

    report = response.output_text
    openai_client.conversations.delete(conversation_id=conversation.id)
    client.close()
    return report


def run_claims_workflow(triage_agent: str, decision_agent: str, content_agent:str, resend_agent:str) -> dict:
    """Orchestrate: triage all claims -> per-claim decision -> consolidated report."""
    triage_report = run_claims_triage(triage_agent)
    print(triage_report)

    print("\n=== Step 2b: Claims Decisions ===")
    decisions = {}
    flagged_claims = []
    contents = {}
    send_reports = {}

    for claim_id in CLAIMS:
        result = json.loads(assess_claim(claim_id))
        if result.get("flags"):
            flagged_claims.append(claim_id)
            print(f"  Deciding on {claim_id}...")
            decision = run_claims_decision(decision_agent, claim_id, result["flags"])
            decisions[claim_id] = decision

            content = run_mail_content(content_agent, claim_id, result["flags"], decisions)
            contents[claim_id] = content

            send_report = run_auto_resend(resend_agent, contents)
            send_reports[claim_id] = send_report


    return {
        "triage_report": triage_report,
        "flagged_claims": flagged_claims,
        "decisions": decisions,
        "contents": contents,
        "send_reports": send_reports,
        "total_claims": len(CLAIMS),
        "problematic_claims": len(flagged_claims),
    }


def print_claims_report(report: dict):
    print("\n" + "=" * 60)
    print("CLAIMSIGHT — CLAIMS PROCESSING REPORT")
    print("=" * 60)
    print(f"  Claims assessed    : {report['total_claims']}")
    print(f"  Claims flagged     : {report['problematic_claims']}")

    if report["flagged_claims"]:
        print(f"  Flagged claims     : {', '.join(report['flagged_claims'])}")
        print("\n--- Decisions ---")
        for claim_id, decision in report["decisions"].items():
            print(f"\n{claim_id}:")
            print(decision)
            print(report["contents"][claim_id])
            print(report["send_reports"][claim_id])
    else:
        print("\n  All claims passed triage — no flags detected.")

    print("=" * 60)


def create_workflow_agent(workflow_agent_name: str = "claims-processing-workflow") -> str:
    """
    Create a workflow agent via the SDK using WorkflowAgentDefinition.

    The workflow appears in the Foundry portal under Build → Agents (kind: workflow).
    Requires allow_preview=True on AIProjectClient.

    Note: WorkflowAgentDefinition agents are visible in the Foundry portal
    and can be invoked from the portal UI. Programmatic invocation via the
    Responses API returns a 'wfresp_' tracking object.

    Returns:
        The workflow agent name.
    """
    from azure.ai.projects import AIProjectClient
    from azure.ai.projects.models import WorkflowAgentDefinition
    from azure.identity import DefaultAzureCredential

    client = AIProjectClient(
        endpoint=PROJECT_CONNECTION_STRING,
        credential=DefaultAzureCredential(),
        allow_preview=True,
    )

    # Exact portal YAML format: flat InvokeAzureAgent actions with agent.name,
    # conversationId, input/output, and a final EndConversation action.
    workflow_yaml = (
        "kind: Workflow\n"
        f"name: {workflow_agent_name}\n"
        "description: Vehicle company churn analysis claim processing - triage then decide then generate content then resend mail\n"
        "trigger:\n"
        "  kind: OnConversationStart\n"
        "  id: trigger_start\n"
        "  actions:\n"
        "    - kind: InvokeAzureAgent\n"
        "      id: step_triage\n"
        "      agent:\n"
        "        name: churn-triage-agent\n"
        "      conversationId: =System.ConversationId\n"
        "      input:\n"
        '        messages: ""\n'
        "      output:\n"
        "        autoSend: true\n"
        "    - kind: InvokeAzureAgent\n"
        "      id: step_decide\n"
        "      agent:\n"
        "        name: churn-decision-agent\n"
        "      conversationId: =System.ConversationId\n"
        "      input:\n"
        '        messages: ""\n'
        "      output:\n"
        "        autoSend: true\n"
        "    - kind: InvokeAzureAgent\n"
        "      id: step_content\n"
        "      agent:\n"
        "        name: email-content-agent\n"
        "      conversationId: =System.ConversationId\n"
        "      input:\n"
        '        messages: ""\n'
        "      output:\n"
        "        autoSend: true\n"
        "    - kind: InvokeAzureAgent\n"
        "      id: step_send\n"
        "      agent:\n"
        "        name: auto-send-agent\n"
        "      conversationId: =System.ConversationId\n"
        "      input:\n"
        '        messages: ""\n'
        "      output:\n"
        "        autoSend: true\n"
        "    - kind: EndConversation\n"
        "      id: step_end\n"
    )

    existing_names = {a.name for a in client.agents.list()}
    if workflow_agent_name in existing_names:
        result = client.agents.create_version(
            agent_name=workflow_agent_name,
            definition=WorkflowAgentDefinition(workflow=workflow_yaml),
            description="Vehicle company churn analysis claims workflow (SDK-created)",
        )
        print(f"  Updated workflow agent: {result.name} (version {result.version})")
    else:
        result = client.agents.create_version(
            agent_name=workflow_agent_name,
            definition=WorkflowAgentDefinition(workflow=workflow_yaml),
            description="Vehicle company churn analysis claims workflow (SDK-created)",
        )
        print(f"  Created workflow agent: {result.name} (version {result.version})")
    print(f"  Visible in Foundry portal → Build → Agents (kind: workflow)")
    client.close()
    return result.name


def run_portal_workflow(workflow_name: str) -> str:
    """
    Invoke a WorkflowAgentDefinition agent via the Responses API.

    Embeds the claims data directly in the input so the claims-triage-agent
    can process all claims without needing to call the assess_claim tool
    (workflow steps cannot handle function-call loops). Both agents execute
    sequentially.

    Returns:
        The workflow's combined text output.
    """
    import time
    from azure.ai.projects import AIProjectClient
    from azure.identity import DefaultAzureCredential

    client = AIProjectClient(
        endpoint=PROJECT_CONNECTION_STRING,
        credential=DefaultAzureCredential(),
        allow_preview=True,
    )
    openai_client = client.get_openai_client()

    print(f"\n=== Portal Workflow: {workflow_name} ===")

    portal_base = PROJECT_CONNECTION_STRING.split("/api/projects/")[0] if "/api/projects/" in PROJECT_CONNECTION_STRING else ""
    if portal_base:
        print(f"\n  View in Foundry portal:")
        print(f"  {portal_base.replace('services.ai.azure.com', 'ai.azure.com')}/build/agents")

    print(f"\n  Workflow steps:")
    print(f"    1. churn-triage-agent    — triage churn analysis for vehicle owners")
    print(f"    2. churn-decision-agent  — recommend action and give reasoning for claims")
    print(f"    3. email-content-agent  — generate promotion content for each claims")
    print(f"    4. auto-send-agent  — use resend tool to send promotion mail to customers")

    # Embed claims data in the input so agents don't need tool calls.
    # The claims-triage-agent is instructed to call assess_claim per claim,
    # but workflow steps cannot handle function-call loops. We provide all claim
    # details upfront and explicitly instruct the agent to work from the provided data.
    with open(CLAIMS_DATA_PATH, "r") as f:
        claims_data = json.load(f)
    claims_text = json.dumps(claims_data["claims"], indent=2)
    query = (
        "All claims data for today is provided below — do NOT call assess_claim. "
        "Analyse the data directly from this message.\n\n"
        + claims_text
        + "\n\nFor each claim, assess churn risk, and "
        "classify churn risk (low/medium/high). Then make a clear recommendation action"
        "decision for each claim with explaination."
    )

    conversation = openai_client.conversations.create()
    print(f"\n  Submitting workflow run (background)...")

    resp = openai_client.responses.create(
        conversation=conversation.id,
        extra_body={"agent_reference": {"name": workflow_name, "type": "agent_reference"}},
        input=query,
        background=True,
    )
    print(f"  Response ID : {resp.id}")
    print(f"  Initial status: {resp.status}")

    output_text = ""
    for attempt in range(12):
        time.sleep(8)
        r = openai_client.responses.retrieve(resp.id)
        tokens = getattr(r.usage, "total_tokens", 0)
        print(f"  [{attempt + 1}] status={r.status}  tokens={tokens}")
        if r.status in ("completed", "failed", "cancelled"):
            output_text = r.output_text
            break

    if output_text:
        print("\nWorkflow output:")
        print(output_text)
    else:
        print(
            "\n  Note: Workflow invocation returned no text output via the API.\n"
            "  The agent is deployed and visible in Foundry portal → Build → Agents."
        )

    openai_client.conversations.delete(conversation_id=conversation.id)
    client.close()
    return output_text


def main():
    if not PROJECT_CONNECTION_STRING:
        print("PROJECT_CONNECTION_STRING not set. Run challenge 0 first!")
        sys.exit(1)

    # --- Part A: Python orchestration (agents called step-by-step from code) ---
    triage_agent, decision_agent = ensure_agents_deployed()
    report = run_claims_workflow(triage_agent, decision_agent)
    print_claims_report(report)

    print("\nWorkflow complete! Agents remain deployed for future runs.")

    # --- Part B: SDK workflow creation + portal invocation ---
    print("\n" + "=" * 60)
    print("CREATING WORKFLOW AGENT VIA SDK")
    print("=" * 60)
    workflow_name = WORKFLOW_AGENT_NAME if WORKFLOW_AGENT_NAME and not WORKFLOW_AGENT_NAME.startswith("<") else "claims-processing-workflow"
    workflow_name = create_workflow_agent(workflow_agent_name=workflow_name)

    print("\n" + "=" * 60)
    print("INVOKING WORKFLOW (BACKGROUND POLL)")
    print("=" * 60)
    run_portal_workflow(workflow_name)

    print("\n" + "=" * 60)
    print("CHALLENGE 4 COMPLETE")
    print("=" * 60)
    print("  Part A: Multi-agent SDK orchestration  ✓")
    print(f"  Part B: Workflow agent deployed        ✓  ({workflow_name})")
    print("          → View in Foundry portal → Build → Agents")


if __name__ == "__main__":
    main()
